name: request_logger
description: A logger middleware for shelf and dart_frog
version: 0.0.1-dev.1
repository: https://github.com/mtwichel/request_logger
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies: 
  collection: ^1.16.0
  http: ^0.13.4
  shelf: ^1.3.1
  stack_trace: ^1.10.0

dev_dependencies:
  meta: ^1.8.0
  mocktail: ^0.3.0
  test: ^1.19.2
  test_process: ^2.0.2
  very_good_analysis: ^3.0.1
