name: dart_frog_logger_example
description: An Dart Frog application demonstrating using RequestLogger
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev
  request_logger:
    path: ../..

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
